In [4]:
import pandas as pd
import scipy as sp
import scipy.stats
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import sklearn as sk
import requests
import time
from sklearn.model_selection import train_test_split
from sklearn import linear_model 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import RobustScaler

In [5]:
#데이터 가져오기
df = pd.read_csv("raw_data/df_grouped_rate.csv", encoding ='utf-8')
cgoongu = pd.read_csv("raw_data/cgoongoo1.csv", encoding ='utf-8')

In [6]:
df_merged = pd.merge(df, cgoongu, on=['district'])
df_merged.drop(['district'], axis=1, inplace =True)

In [7]:
df_merged.columns

Index(['year', 'code', 'sales_total', 's_store_no_of_store',
       's_store_no_of_opening', 's_store_no_of_closing', 's_work_female_40s',
       's_work_female_50s', 's_work_female_60s', 'b_facil_total',
       's_float_male', 's_float_female', 'b_apt_avg_price',
       'b_income_avg_monthly_inc', 's_work_female', 's_work_male',
       'sales_weekday', 'sales_female', 'sales_2030s', 'sales_06_11',
       'sales_11_14', 'sales_14_17', 'sales_17_21', 'sales_21_24', 'cgoongoo'],
      dtype='object')

In [8]:
df_cgoongu_gb=df_merged.groupby(['year','cgoongoo', 'code']).agg({
    "sales_total":"sum",
    "s_store_no_of_store":"sum", #이걸 mean으로 해야할지 고민이 필요
    "s_store_no_of_opening":"sum",
    "s_store_no_of_closing":"sum",
    "sales_weekday":"sum",
    "sales_female":"sum",
    "sales_2030s":"sum",
    "sales_06_11":"sum",
    "sales_11_14":"sum",
    "sales_14_17":"sum",
    "sales_17_21":"sum",
    "sales_21_24":"sum",
    "s_work_female_40s":"mean",
    "s_work_female_50s":"mean",
    "s_work_female_60s":"mean",
    "b_facil_total":"mean",
    "s_float_male":"mean",
    "s_float_female":"mean",
    'b_apt_avg_price':'mean',
    'b_income_avg_monthly_inc':'mean',
    's_work_female':'mean',
    's_work_male':'mean',
    'b_income_avg_monthly_inc':'mean'
    
})
df_cgoongu_gb.tail(3)

                         sales_total  s_store_no_of_store  \
year cgoongoo code
2019 11740    CS300015  5.912349e+09                   49
              CS300016  5.516874e+09                  496
              CS300017  2.322398e+09                   95

                        s_store_no_of_opening  s_store_no_of_closing  \
year cgoongoo code
2019 11740    CS300015                      1                      1
              CS300016                      8                      7
              CS300017                      0                      1

                        sales_weekday  sales_female  sales_2030s  sales_06_11  \
year cgoongoo code
2019 11740    CS300015       4.290286      3.237088     0.762611     0.080720
              CS300016      25.429959      9.793725     6.189211     7.338632
              CS300017       5.827562      4.553235     3.578226     0.315342

                        sales_11_14  sales_14_17  ...  s_work_female_40s  \
year cgoongoo code                                ...
2019 11740    CS300015     2.089863     2.577843  ...             64.250
              CS300016     7.644050    10.612261  ...             50.375
              CS300017     3.444519     3.303651  ...             51.000

                        s_work_female_50s  s_work_female_60s  b_facil_total  \
year cgoongoo code
2019 11740    CS300015          64.083333          34.333333     112.500000
              CS300016          51.750000          28.187500     108.156250
              CS300017          52.722222          33.666667     118.888889

                         s_float_male  s_float_female  b_apt_avg_price  \
year cgoongoo code
2019 11740    CS300015  194778.250000   189097.833333     2.004435e+08
              CS300016  158058.328125   154031.750000     1.826516e+08
              CS300017  167489.388889   165458.055556     1.682300e+08

                        b_income_avg_monthly_inc  s_work_female  s_work_male
year cgoongoo code
2019 11740    CS300015              3.384987e+06     253.500000   274.166667
              CS300016              3.370583e+06     205.921875   221.187500
              CS300017              3.212065e+06     216.277778   193.944444

[3 rows x 22 columns]

In [9]:
# # df 저장
# #index에 names=['year', 'cgoongoo', 'code']가 들어있다
# df_cgoongu_gb.to_csv('raw_data/df_cgoongu_gb.csv', index=True, encoding='utf-8')

In [10]:
df_cgoongu_gb.reset_index(inplace=True)

In [12]:
df_cgoongu_gb.head()

,year,cgoongoo,code,sales_total,s_store_no_of_store,s_store_no_of_opening,s_store_no_of_closing,sales_weekday,sales_female,sales_2030s,...,s_work_female_40s,s_work_female_50s,s_work_female_60s,b_facil_total,s_float_male,s_float_female,b_apt_avg_price,b_income_avg_monthly_inc,s_work_female,s_work_male
0,2018,11110,CS100001,4.711364e+10,624,22,30,17.282523,7.734313,7.488426,...,58.333333,44.833333,17.708333,145.250000,70010.583333,70020.875000,2.194223e+08,3.878552e+06,239.875000,276.708333
1,2018,11110,CS100002,3.764873e+09,55,5,3,8.872807,3.788772,4.428286,...,66.166667,49.833333,18.916667,161.166667,79649.458333,76463.958333,2.364741e+08,3.766325e+06,271.416667,332.666667
2,2018,11110,CS100003,3.625603e+09,54,2,1,8.907585,4.313511,5.107181,...,62.909091,46.363636,19.181818,155.272727,88827.045455,89418.727273,2.027983e+08,3.760143e+06,273.818182,264.727273
3,2018,11110,CS100004,1.541111e+10,187,4,6,11.915524,6.677956,7.564242,...,68.058824,47.000000,16.470588,150.823529,65091.500000,65892.588235,2.618564e+08,4.032644e+06,273.235294,278.529412
4,2018,11110,CS100005,7.559278e+09,222,23,10,12.324600,7.842999,7.735840,...,53.235294,40.294118,17.764706,164.411765,79970.441176,79983.970588,2.035326e+08,3.719739e+06,228.000000,280.000000

In [23]:
scale_columns

['cgoongoo',
 'sales_total',
 's_store_no_of_store',
 's_store_no_of_opening',
 's_store_no_of_closing',
 'sales_weekday',
 'sales_female',
 'sales_2030s',
 'sales_06_11',
 'sales_11_14',
 'sales_14_17',
 'sales_17_21',
 'sales_21_24',
 's_work_female_40s',
 's_work_female_50s',
 's_work_female_60s',
 'b_facil_total',
 's_float_male',
 's_float_female',
 'b_apt_avg_price',
 'b_income_avg_monthly_inc',
 's_work_female',
 's_work_male']

In [24]:
#로버스트 스케일링
from sklearn.preprocessing import RobustScaler
scale_columns = [i for i in df_cgoongu_gb.columns if i not in ['year', 'cgoongoo', 'code',]]

rb = RobustScaler()
rb.fit(df_cgoongu_gb[scale_columns])
df_robust_scaled = rb.transform(df_cgoongu_gb[scale_columns])
df_robust_scaled = pd.DataFrame(df_robust_scaled, columns=scale_columns)
df_robust_scaled2= pd.concat([df_cgoongu_gb[['cgoongoo','code']],df_robust_scaled], axis=1)
df_robust_scaled.columns
model= sm.OLS.from_formula("sales_total ~ C(cgoongoo) +C(code) +"+" + ".join(scale_columns[2:]), data=df_robust_scaled2)
result =  model.fit()
print(result.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            sales_total   R-squared:                       0.836
Model:                            OLS   Adj. R-squared:                  0.829
Method:                 Least Squares   F-statistic:                     123.1
Date:                Thu, 26 Dec 2019   Prob (F-statistic):               0.00
Time:                        17:12:19   Log-Likelihood:                -2508.2
No. Observations:                2220   AIC:                             5194.
Df Residuals:                    2131   BIC:                             5702.
Df Model:                          88
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
Intercept                    2.1000      0.252      8.350      0.000       1.607       2.593
C(cgoongoo)[T.11140]        -0.0154      0.138     -0.111      0.911      -0.286       0.255
C(cgoongoo)[T.11170]         0.3583      0.197      1.822      0.069      -0.027       0.744
C(cgoongoo)[T.11200]         0.1207      0.173      0.698      0.485      -0.218       0.460
C(cgoongoo)[T.11215]         0.2131      0.158      1.345      0.179      -0.098       0.524
C(cgoongoo)[T.11230]         0.0654      0.171      0.383      0.702      -0.269       0.400
C(cgoongoo)[T.11260]         0.1872      0.157      1.191      0.234      -0.121       0.496
C(cgoongoo)[T.11290]        -0.0651      0.157     -0.414      0.679      -0.373       0.243
C(cgoongoo)[T.11305]         0.1165      0.163      0.716      0.474      -0.203       0.436
C(cgoongoo)[T.11320]         0.3923      0.186      2.104      0.035       0.027       0.758
C(cgoongoo)[T.11350]         0.1349      0.161      0.839      0.402      -0.180       0.450
C(cgoongoo)[T.11380]         0.1446      0.174      0.833      0.405      -0.196       0.485
C(cgoongoo)[T.11410]         0.0967      0.157      0.615      0.539      -0.212       0.405
C(cgoongoo)[T.11440]         0.1304      0.163      0.800      0.424      -0.189       0.450
C(cgoongoo)[T.11470]         0.1288      0.170      0.757      0.449      -0.205       0.463
C(cgoongoo)[T.11500]         0.1507      0.169      0.892      0.373      -0.181       0.482
C(cgoongoo)[T.11530]         0.3375      0.173      1.948      0.052      -0.002       0.677
C(cgoongoo)[T.11545]         0.2705      0.172      1.576      0.115      -0.066       0.607
C(cgoongoo)[T.11560]         0.1596      0.170      0.938      0.349      -0.174       0.493
C(cgoongoo)[T.11590]         0.1920      0.156      1.233      0.218      -0.113       0.497
C(cgoongoo)[T.11620]         0.2150      0.178      1.209      0.227      -0.134       0.564
C(cgoongoo)[T.11650]         0.3378      0.220      1.535      0.125      -0.094       0.769
C(cgoongoo)[T.11680]         0.6770      0.230      2.945      0.003       0.226       1.128
C(cgoongoo)[T.11710]         0.3664      0.162      2.265      0.024       0.049       0.684
C(cgoongoo)[T.11740]         0.0571      0.166      0.344      0.731      -0.269       0.383
C(code)[T.CS100002]         -2.7544      0.218    -12.629      0.000      -3.182      -2.327
C(code)[T.CS100003]         -2.4192      0.230    -10.531      0.000      -2.870      -1.969
C(code)[T.CS100004]         -2.2352      0.237     -9.421      0.000      -2.701      -1.770
C(code)[T.CS100005]         -3.6852      0.217    -16.945      0.000      -4.112      -3.259
C(code)[T.CS100006]         -2.3450      0.238     -9.873      0.000      -2.811      -1.879
C(code)[T.CS100007]         -2.4275      0.252     -9.625      0.000      -2.922      -1.933
C(code)[T.CS100008]         -2.2654      0.252     -8.993      0.000      -2.759      -1.771
C(code)[T.CS100009]         -3.7002      0.261    -14.189      0.000      -4.212      -3.189
C(code)[T.CS100010]         -2.9643      0.284    -10.445      0.000      -3.521      -2.408
C(code)[T.CS200001]         -1.2788      0.263     -4.856      0.000      -1.795      -0.762
C(code)[T.CS200002]         -1.9715      0.259     -7.611      0.000      -2.480      -1.464
C(code)[T.CS200003]         -2.3248      0.289     -8.055      0.000      -2.891      -1.759
C(code)[T.CS200004]         -1.7154      0.263     -6.525      0.000      -2.231      -1.200
C(code)[T.CS200005]         -2.1406      0.260     -8.241      0.000      -2.650      -1.631
C(code)[T.CS200006]         -1.1142      0.281     -3.964      0.000      -1.665      -0.563
C(code)[T.CS200007]         -2.2304      0.258     -8.635      0.000      -2.737      -1.724
C(code)[T.CS200008]         -2.4014      0.280     -8.578      0.000      -2.950      -1.852
C(code)[T.CS200009]         -2.5877      0.257    -10.054      0.000      -3.092      -2.083
C(code)[T.CS200010]         -3.1992      0.279    -11.454      0.000      -3.747      -2.651
C(code)[T.CS200011]         -2.2874      0.268     -8.544      0.000      -2.812      -1.762
C(code)[T.CS200012]         -2.8431      0.248    -11.444      0.000      -3.330      -2.356
C(code)[T.CS200013]         -2.8566      0.256    -11.144      0.000      -3.359      -2.354
C(code)[T.CS200014]         -2.3607      0.248     -9.535      0.000      -2.846      -1.875
C(code)[T.CS200015]         -2.5956      0.258    -10.072      0.000      -3.101      -2.090
C(code)[T.CS200016]         -2.5950      0.254    -10.214      0.000      -3.093      -2.097
C(code)[T.CS200017]         -2.0439      0.269     -7.593      0.000      -2.572      -1.516
C(code)[T.CS200018]         -2.3709      0.258     -9.183      0.000      -2.877      -1.865
C(code)[T.CS300001]          0.1441      0.240      0.601      0.548      -0.326       0.614
C(code)[T.CS300002]          0.4289      0.302      1.421      0.155      -0.163       1.021
C(code)[T.CS300003]         -2.3680      0.257     -9.224      0.000      -2.871      -1.865
C(code)[T.CS300004]         -2.3906      0.250     -9.551      0.000      -2.881      -1.900
C(code)[T.CS300005]         -1.9446      0.237     -8.195      0.000      -2.410      -1.479
C(code)[T.CS300006]         -2.2839      0.257     -8.888      0.000      -2.788      -1.780
C(code)[T.CS300007]         -2.0208      0.266     -7.596      0.000      -2.542      -1.499
C(code)[T.CS300008]         -2.0716      0.248     -8.370      0.000      -2.557      -1.586
C(code)[T.CS300009]         -1.0218      0.267     -3.827      0.000      -1.545      -0.498
C(code)[T.CS300010]         -2.4175      0.254     -9.534      0.000      -2.915      -1.920
C(code)[T.CS300011]         -2.5573      0.252    -10.142      0.000      -3.052      -2.063
C(code)[T.CS300012]         -2.0350      0.252     -8.074      0.000      -2.529      -1.541
C(code)[T.CS300013]         -2.1510      0.255     -8.419      0.000      -2.652      -1.650
C(code)[T.CS300014]         -2.6164      0.251    -10.430      0.000      -3.108      -2.125
C(code)[T.CS300015]         -1.3898      0.254     -5.470      0.000      -1.888      -0.892
C(code)[T.CS300016]         -3.2307      0.272    -11.889      0.000      -3.764      -2.698
C(code)[T.CS300017]         -1.9286      0.259     -7.451      0.000      -2.436      -1.421
s_store_no_of_opening        0.0316      0.029      1.078      0.281      -0.026       0.089
s_store_no_of_closing        0.5149      0.029     17.614      0.000       0.458       0.572
sales_weekday                0.4343      0.237      1.830      0.067      -0.031       0.900
sales_female                -0.7090      0.120     -5.898      0.000      -0.945      -0.473
sales_2030s                  0.0853      0.074      1.151      0.250      -0.060       0.231
sales_06_11                  0.2843      0.060      4.748      0.000       0.167       0.402
sales_11_14                  0.3520      0.100      3.509      0.000       0.155       0.549
sales_14_17                 -0.0980      0.123     -0.796      0.426      -0.339       0.143
sales_17_21                  0.1200      0.122      0.985      0.325      -0.119       0.359
sales_21_24                  0.0512      0.075      0.681      0.496      -0.096       0.199
s_work_female_40s            0.0357      0.126      0.284      0.777      -0.211       0.282
s_work_female_50s           -0.0032      0.062     -0.053      0.958      -0.124       0.117
s_work_female_60s           -0.0051      0.040     -0.127      0.899      -0.084       0.074
b_facil_total                0.0996      0.039      2.553      0.011       0.023       0.176
s_float_male                 0.0636      0.098      0.651      0.515      -0.128       0.255
s_float_female              -0.0603      0.108     -0.560      0.575      -0.271       0.151
b_apt_avg_price             -0.0550      0.056     -0.982      0.326      -0.165       0.055
b_income_avg_monthly_inc     0.2235      0.060      3.702      0.000       0.105       0.342
s_work_female               -0.0858      0.121     -0.708      0.479      -0.324       0.152
s_work_male                  0.0242      0.100      0.242      0.808      -0.172       0.220
==============================================================================
Omnibus:                     1471.274   Durbin-Watson:                   1.857
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            55737.753
Skew:                           2.587   Prob(JB):                         0.00
Kurtosis:                      26.996   Cond. No.                         275.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.